apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-app.name" . }}-{{ .Release.Name }}
  labels:
    {{- include "service-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "service-app.selectorLabels" . | nindent 4 }}