replicaCount: 1

image:
  repository: saakbar/service-app
  pullPolicy: IfNotPresent
  tag: "v1.1.0"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

config:
  apiBaseUrl: "http://{{ .Release.Name }}-backend:5000"